Repository invictus-integration/docs-ifa, pull requests merged in 2025-03, with the labels that each got.

#274 docs: v6 migration updates
  framework/components/matrix.md
  framework/components/pubsub.md
  framework/components/pubsubV2.md
  framework/components/transco.md
  framework/components/transcoV2.md
  support/v6-migration.md
Labels: documentation, enhancement

#280 docs(groups): simplify ad access + group sync
  _sidebar.md
  dashboard/azureADSetup.md
  dashboard/groupmanagement.md
  images/dashboard/Groups/groupman_1.jpg
  images/dashboard/azureAD/aad1.JPG
  images/dashboard/azureAD/aad10.png
  images/dashboard/azureAD/aad11.png
  images/dashboard/azureAD/aad12.png
  images/dashboard/azureAD/aad13.jpg
  images/dashboard/azureAD/aad15.jpg
  images/dashboard/azureAD/aad2.JPG
  images/dashboard/azureAD/aad4.JPG
  images/dashboard/azureAD/aad5.JPG
  images/dashboard/azureAD/aad6.JPG
  images/dashboard/azureAD/aad7.JPG
  images/dashboard/azureAD/aad8.JPG
  images/dashboard/azureAD/aad9.png
Labels: documentation

#279 docs(first-time-login): simplify get temp admin pass
  dashboard/setup.md
  images/dashboard/AdminAccount/adminAccount-1.jpg
  images/dashboard/AdminAccount/adminAccount-2.jpg
  images/dashboard/AdminAccount/adminAccount-3.jpg
Labels: documentation

#282 docs(flows): centralize edit flow page
  _sidebar.md
  dashboard/alerting.md
  dashboard/editflows.md
  dashboard/foldersflows.md
  images/v2_alerting4.png
  images/v2_dsb-createflow.png
Labels: enhancement
