Repository invictus-integration/docs-ifa, pull requests merged in 2025-07, with the labels that each got.

#395 fix(logo): use markdown for referencing light/dark logo
  src/css/custom.css
  static/img/invictus.dark.png
  static/img/invictus.index.dark.png
  static/img/invictus.index.light.png
  static/img/invictus.light.png
  versioned_docs/version-v6.0.0/index.md
Labels: bug, documentation

#396 chore(exn.handler): use simpler diagram for exception handler component
  static/images/framework/logic-app-setup-w-exception-handler.png
  versioned_docs/version-v6.0.0/framework/exceptionHandler.mdx
  versioned_docs/version-v6.0.0/framework/exceptionhandler.drawio.svg
Labels: documentation, enhancement

#401 docs(entra): Clarify scope naming in documentation
  versioned_docs/version-v6.0.0/dashboard/installation/01_give_ad_access.md
Labels: documentation

#399 docs(flow.trace): correct flow trace search visualization
  static/images/dashboard/regex.png
  static/images/dashboard/search-for-flow-traces-advanced-search.gif
  static/images/dashboard/search-for-flow-traces-basic-search.gif
  static/images/v2_search-advanced1.png
  static/images/v2_search-basic1.png
  static/images/v2_search-basic2.png
  versioned_docs/version-v6.0.0/dashboard/flows/02_search.mdx
Labels: bug, documentation

#406 chore(flow): centralize flow crud on single page
  src/css/custom.css
  static/images/v2_folderpermissions1.png
  versioned_docs/version-v6.0.0/dashboard/flows/01_add.md
  versioned_docs/version-v6.0.0/dashboard/flows/01_add.mdx
  versioned_docs/version-v6.0.0/dashboard/flows/03_permissions.mdx
  versioned_docs/version-v6.0.0/dashboard/installation/02_sync_ad_groups.md
Labels: documentation, enhancement

#411 chore(flowtrace.la): move custom flow operations to import flow trace via la page
  static/images/v2_custom-resumeresubmit-createflow.png
  static/images/v2_custom-resumeresubmit-editflow.png
  static/images/v2_custom-resumeresubmit-flowscreen-advancedsettings-headers-button.png
  static/images/v2_custom-resumeresubmit-flowscreen-advancedsettings-headers-dialog-inputted-header-delete-icon.png
  static/images/v2_custom-resumeresubmit-flowscreen-advancedsettings-testurl-button.png
  versioned_docs/version-v6.0.0/architecture-diagram.md
  versioned_docs/version-v6.0.0/dashboard/flows/01_add.mdx
  versioned_docs/version-v6.0.0/dashboard/flows/02_search.mdx
  versioned_docs/version-v6.0.0/dashboard/flows/04_import-flow-traces/custom-resumeresubmit.md
  versioned_docs/version-v6.0.0/dashboard/flows/04_import-flow-traces/import-flows-via-la.mdx
Labels: documentation, enhancement

#408 fix(bicep): add missing container apps framework/dashboard parameters
  versioned_docs/version-v6.0.0/dashboard/flows/04_import-flow-traces/import-flows-via-la.mdx
  versioned_docs/version-v6.0.0/dashboard/installation/dashboard-releasepipeline.mdx
  versioned_docs/version-v6.0.0/framework/installation/framework-releasepipeline.mdx
Labels: bug, documentation

#410 chore(docusaurus): use v6 io v6.0.0 in navbar dropdown
  docusaurus.config.js
Labels: documentation, enhancement

#413 chore(seqctrl): streamline motivation & endpoints
  versioned_docs/version-v6.0.0/dashboard/flows/04_import-flow-traces/import-flow-prog-via-eh.md
  versioned_docs/version-v6.0.0/dashboard/flows/04_import-flow-traces/import-flow-prog-via-http.md
  versioned_docs/version-v6.0.0/framework/sequencecontroller.md
Labels: documentation, enhancement

#412 chore(transco.v2): move matrix basic promote v2 to transco v2 page
  versioned_docs/version-v6.0.0/framework/deprecated/matrix-basic.md
  versioned_docs/version-v6.0.0/framework/deprecated/matrix-promote.md
  versioned_docs/version-v6.0.0/framework/deprecated/matrix.md
  versioned_docs/version-v6.0.0/framework/transcoV2-Matrix.md
  versioned_docs/version-v6.0.0/framework/transcoV2.mdx
Labels: documentation, enhancement

#407 chore(pubsub.v2): add should-delete-on-receive usage warning
  versioned_docs/version-v6.0.0/framework/pubsubV2.md
Labels: documentation, enhancement

#417 chore(installation): use installation wizard for dashboard/framework
  src/components/InstallationWizard.js
  versioned_docs/version-v6.0.0/dashboard/accesscontrolrights.md
  versioned_docs/version-v6.0.0/dashboard/flows/01_add.mdx
  versioned_docs/version-v6.0.0/dashboard/flows/04_import-flow-traces/import-flows-via-la.mdx
  versioned_docs/version-v6.0.0/dashboard/installation/03_first-time-login.md
  versioned_docs/version-v6.0.0/dashboard/installation/03_give_la_access.md
  versioned_docs/version-v6.0.0/dashboard/installation/dashboard-buildpipeline.md
  versioned_docs/version-v6.0.0/dashboard/installation/dashboard-migration.md
  versioned_docs/version-v6.0.0/dashboard/installation/dashboard-releasepipeline.mdx
  versioned_docs/version-v6.0.0/dashboard/installation/dashboard-vnet.md
  versioned_docs/version-v6.0.0/dashboard/installation/index.md
  versioned_docs/version-v6.0.0/dashboard/installation/index.mdx
  versioned_docs/version-v6.0.0/dashboard/installation/pipelines/dashboard.build.yaml
  versioned_docs/version-v6.0.0/dashboard/installation/pipelines/dashboard.release.yaml
  versioned_docs/version-v6.0.0/dashboard/installation/scripts/invictusVnetDNSZones.json
  versioned_docs/version-v6.0.0/framework/exceptionHandler.mdx
  versioned_docs/version-v6.0.0/framework/installation/_category_.yml
  versioned_docs/version-v6.0.0/framework/installation/framework-buildpipeline.md
  versioned_docs/version-v6.0.0/framework/installation/framework-migration.md
  versioned_docs/version-v6.0.0/framework/installation/framework-releasepipeline.mdx
  versioned_docs/version-v6.0.0/framework/installation/index.md
  versioned_docs/version-v6.0.0/framework/installation/index.mdx
  versioned_docs/version-v6.0.0/framework/installation/pipelines/framework.build.yaml
  versioned_docs/version-v6.0.0/framework/installation/pipelines/framework.release.yaml
  versioned_docs/version-v6.0.0/framework/timesequencer.md
  versioned_docs/version-v6.0.0/framework/xsd-validator.md
  versioned_docs/version-v6.0.0/index.md
  versioned_docs/version-v6.0.0/scripts/Invictus-GetSources.ps1
  versioned_docs/version-v6.0.0/scripts/invictusVnetDNSZones.bicep
  versioned_docs/version-v6.0.0/support/v6-migration.md
Labels: documentation, enhancement

#418 chore(users): use breadcrumb + admin badge on users page
  src/components/OnlyAdminsBadge.js
  static/images/dashboard/ForgotPassword/ForgotPassword_0.jpg
  static/images/dashboard/ForgotPassword/ForgotPassword_2.jpg
  static/images/dashboard/ForgotPassword/ForgotPassword_3.jpg
  static/images/dashboard/ForgotPassword/ForgotPassword_4.jpg
  static/images/dashboard/ForgotPassword/ForgotPassword_5.jpg
  static/images/dashboard/ForgotPassword/ForgotPassword_6.jpg
  static/images/dashboard/ForgotPassword/ForgotPassword_8.jpg
  static/images/dashboard/settings-page-as-admin.png
  versioned_docs/version-v6.0.0/dashboard/flows/02_search.mdx
  versioned_docs/version-v6.0.0/dashboard/security/01_users.mdx
  versioned_docs/version-v6.0.0/dashboard/security/04_auditing.mdx
  versioned_docs/version-v6.0.0/dashboard/settings.md
Labels: documentation, enhancement

#422 chore(sequencing): streamling seq ctrl & time seq w workflow runs diagrams
  static/images/framework/pseudo-logic-app-w-sequence-controller.png
  static/images/framework/pseudo-logic-app-workflow-runs-w-sequence-controller.png
  static/images/framework/pseudo-logic-app-workflow-runs-w-time-sequencer.png
  versioned_docs/version-v6.0.0/framework/sequencecontroller.md
  versioned_docs/version-v6.0.0/framework/timesequencer.md
Labels: documentation, enhancement

#424 docs(xml.json.converter): streamline xml-json converter page
  versioned_docs/version-v6.0.0/framework/xmljsonconverter.md
  versioned_docs/version-v6.0.0/framework/xmljsonconverter.mdx
Labels: documentation, enhancement

#425 chore(folder): use breadcrumb in folder organization
  versioned_docs/version-v6.0.0/dashboard/flows/index.md
Labels: documentation, enhancement

#430 fix(breadcrumb): use md logo link in breadcrumb
  src/css/custom.css
  versioned_docs/version-v6.0.0/dashboard/flows/01_add.mdx
Labels: bug, documentation

#428 chore(groups): move sync groups page to access groups page
  src/components/Walkthrough.tsx
  src/css/custom.css
  static/images/dashboard/Groups/groupman_3.jpg
  static/images/dashboard/Groups/groupman_4.jpg
  static/images/dashboard/Groups/groups-disable-action.png
  static/images/dashboard/Groups/groups-permissions-action.png
  versioned_docs/version-v6.0.0/dashboard/installation/01_give_ad_access.md
  versioned_docs/version-v6.0.0/dashboard/installation/01_give_ad_access.mdx
  versioned_docs/version-v6.0.0/dashboard/installation/02_sync_ad_groups.md
  versioned_docs/version-v6.0.0/dashboard/installation/index.mdx
  versioned_docs/version-v6.0.0/dashboard/security/01_users.mdx
Labels: documentation, enhancement

#429 chore(auditing): streamline auditing page w/ gif & breadcrumb
  static/images/dashboard/search-for-audits.gif
  static/images/v2_auditing-search.png
  static/images/v2_auditing.png
  versioned_docs/version-v6.0.0/dashboard/security/04_auditing.mdx
Labels: documentation, enhancement

#431 chore(roles): provide a more in-depth role page / func
  versioned_docs/version-v6.0.0/dashboard/security/03_roles.md
Labels: documentation, enhancement

#433 chore(exn.handler): streamline exn handler title w/ description
  versioned_docs/version-v6.0.0/framework/exceptionHandler.mdx
Labels: documentation, enhancement

#439 fix(anchor): correct broken anchor links throughout
  docusaurus.config.js
  versioned_docs/version-v6.0.0/dashboard/installation/01_give_ad_access.mdx
  versioned_docs/version-v6.0.0/dashboard/security/01_users.mdx
  versioned_docs/version-v6.0.0/dashboard/security/03_roles.md
  versioned_docs/version-v6.0.0/framework/deprecated/index.md
  versioned_docs/version-v6.0.0/framework/deprecated/matrix.md
  versioned_docs/version-v6.0.0/framework/deprecated/pubsub.md
  versioned_docs/version-v6.0.0/framework/deprecated/transco.md
  versioned_docs/version-v6.0.0/framework/installation/index.mdx
  versioned_docs/version-v6.0.0/framework/sequencecontroller.md
  versioned_docs/version-v6.0.0/framework/timesequencer.md
  versioned_docs/version-v6.0.0/support/v6-migration.md
Labels: bug, documentation

#436 chore(pubsub.v2): use descriptive title for pubsub v2
  versioned_docs/version-v6.0.0/framework/pubsubV2.md
Labels: documentation, enhancement

#446 chore(transco.v2): add related bicep params for transco v2 component
  versioned_docs/version-v6.0.0/framework/transcoV2.mdx
Labels: documentation, enhancement

#448 chore(flowtrace.la): use walkthrough for import flow traces via la
  versioned_docs/version-v6.0.0/dashboard/flows/04_import-flow-traces/import-flows-via-la.mdx
Labels: documentation, enhancement

#450 fix(breadcrumb): use md logo link in breadcrumb
  versioned_docs/version-v6.0.0/dashboard/flows/02_search.mdx
  versioned_docs/version-v6.0.0/dashboard/security/01_users.mdx
  versioned_docs/version-v6.0.0/dashboard/settings.md
Labels: bug, documentation
